spring:
  datasource:
    url: jdbc:mysql://db:3306/db_fido2?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 7
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379
      password: redis1234

server:
  port: 8081

logging:
  level:
    com.linecorp.line: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

